# Generated by Django 5.0 on 2023-12-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='client_app.client', verbose_name='получатели'),
        ),
    ]
