# Generated by Django 5.0 on 2023-12-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0002_mailing_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemailing',
            name='mailing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mailing_app.mailing'),
            preserve_default=False,
        ),
    ]
