# Generated by Django 5.0 on 2023-12-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0003_messagemailing_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={},
        ),
        migrations.RemoveField(
            model_name='messagemailing',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='email',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailing_app.messagemailing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='finish_time',
            field=models.DateField(verbose_name='окончание рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateField(verbose_name='начало рассылки'),
        ),
    ]
